### ISSUE TITLE
Not working on MKS SBase with smoothieware

### ISSUE THREAD

**Issue by omnilogix** [jneilliii/OctoPrint-BLTouch#1]
I just installed the plugin and there is no action performed when pressing the BLTouch buttons.  All other control buttons are working as normal.  Running OctoPrint 1.3.4 via OctoPi.

**Comment by jneilliii** [comment]
I'm not familiar with the smoothieware commands for BLTouch.  Could you let me know what the gcode is that you use to manually do the different actions with the BLTouch?

**Comment by jneilliii** [comment]
I think I found the commands, but instead decided to add a settings section for entering custom commands as necessary.  If you don't mind testing a custom build, please uninstall previous release and then from plugin manager (...from URL) use the following url to install the plugin. Once installed you'll need to go into settings and set the GCODE commands specific to your firmware configuration.

https://github.com/jneilliii/OctoPrint-BLTouch/archive/dev.zip

**Comment by aziraphale** [comment]
Ah, excellent - I just came here to mention this (or possibly try to butcher together a fork + PR for a version with a settings page for these commands - but my Python skills are pretty poor!).

From when I was setting up my BLTouch probe on Smoothie, there seem to be a few different commands used by different people. Indeed Smoothieware seems to let you set whatever commands you like.

I'm using `M280 S3.0` to lower the probe pin and `M280 S7.0` to raise it again. As for the self-test and alarm-reset commands, I wasn't aware that was even possible to do in software! I've been disconnecting & reconnecting the probe power lines every time it got into an alarm state and was just about to hook up an Octoprint-controlled relay to give me a button to cycle the probe's power ;) So I wonder how those are supposed to work on Smoothieware...

My printer's stuck in a print for another 5 hours, but I'll give the dev version a try once I can safely restart Octoprint.

Thanks for creating this plugin, by the way! :D

**Comment by omnilogix** [comment]
I found the plugin settings by accident, and now it works for me!

1) Download the latest plugin
2) Goto plugin settings for the BLTouch
3) Probe Up: M280 S7.0, Probe Down: M280 S3.0,  Self Test: M280 S8.4, Release Alarm: M280 S10.6
4) Reboot


Thanks, this is a great feature!!

**Comment by omnilogix** [comment]
Thanks for the quick response, I did not respond because it went to my spam folder.   I updated the github issue with command information.   It works great!!

Thanks

**Comment by jneilliii** [comment]
As the newest version in master now has a settings page, this should work for anyone and has been confirmed to be working by @omnillogix.
