### ISSUE TITLE
multi-line / multi-command support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jneilliii/OctoPrint-BLTouch#10]
currently there is no way to issue multiple commands, i.e.:
in order to bind the following snippet to the "Probe Bed" button:
```
G29 P1 ; measure
G29 T ; report
G29 A; activate
```

**Comment by jneilliii** [comment]
Depending on your firmware you can separate the commands with a colon, so try the following from terminal and if it works as expected you can use that in the setting.

`G29 P1 : G29 T : G29 A`

**Comment by Andrei-Pozolotin** [comment]
1. does not work for me in marlin 2.x
2. even if it works, one would have to discard use of comments
3. other octo-plugins use simple one-command-per-line approach, i.e.:
https://plugins.octoprint.org/plugins/customControl/

**Comment by jneilliii** [comment]
No problem, wasn't sure if that would work or not.  I have done it myself with the BedLevelVisualizer plugin so I know the process, just need the time to make the change.

**Comment by Andrei-Pozolotin** [comment]
thank you

**Comment by jneilliii** [comment]
Just released version 0.3.1 that updates the Probe Bed command to allow for multiple lines to be sent to the printer.

**Comment by Andrei-Pozolotin** [comment]
works, thank you.
