### ISSUE TITLE
Reversing Z Home Direction on SKR 1.4 Turbo

### ISSUE THREAD

**Issue by N6MQD** [jneilliii/OctoPrint-BLTouch#15]
Recently rebuilt an A8 to AM8 with an SKR1.4 Turbo connected to RPi 4B running latest Octoprint.  Found the useful plugin for controlling the BLTouch probe and it works as expected except when I home the system, the probe does not deploy and the Z moves positive and not negative.  Manual control via Octoprint works normal.  

Disabled the plugin and the printer works as expected.  Enabled the plugin and the home direction inverted.

**Comment by jneilliii** [comment]
You're more than welcome to look at the code, but I can tell you right now this plugin only sends the commands that you've configured in settings. If the default commands are causing that for you then you may consider changing them to something else.

**Comment by N6MQD** [comment]
Thank you.  First time I’ve posted an issue.  Sends default commands configured in Octoprint or in the Marlin firmware?

Chris

**Comment by jneilliii** [comment]
It sends the command that are configured in the plugin's settings, inside OctoPrint's settings window at the bottom.

![image](https://user-images.githubusercontent.com/5249455/85086689-53b23a00-b1a9-11ea-98d7-d3710b89b798.png)
