### ISSUE TITLE
Installation did not work

### ISSUE THREAD

**Issue by carlosjulianruiz** [jneilliii/OctoPrint-BLTouch#20]
Installing plugin "OctoPrint-BLTouch" from https://github.com/jneilliii/OctoPrint-BLTouch/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmptIgTCh/OctoPrint-BLTouch-master.zip --no-cache-dir --pi pip install "https://github.com/jneilliii/OctoPrint-BLTouch/archive/master.zip"
Usage:
/home/pi/oprint/bin/python2 -m pip install [options] <requirement specifier> [package-index-options] ...
/home/pi/oprint/bin/python2 -m pip install [options] -r <requirements file> [package-index-options] ...
/home/pi/oprint/bin/python2 -m pip install [options] [-e] <vcs project url> ...
/home/pi/oprint/bin/python2 -m pip install [options] [-e] <local project path> ...
/home/pi/oprint/bin/python2 -m pip install [options] <archive url/path> ...
no such option: --pi pip install "https://github.com/jneilliii/OctoPrint-BLTouch/archive/master.zip"
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
that looks like an error introduced by the command line, I have no control over the pip options being used by plugin manager. Do you have additional arguments entered into the plugin manager's pip settings?

![image](https://user-images.githubusercontent.com/5249455/99743201-34df0900-2aa3-11eb-8437-b08afa800ee0.png)
