### ISSUE TITLE
Install not giving all options 

### ISSUE THREAD

**Issue by MarcWinNJ** [jneilliii/OctoPrint-BLTouch#21]
on new install only the Probe Up button appears. I had it on a previous install and it worked. I have deleted and reinstalled on this new install. 
![Screen Shot 2020-11-28 at 2 03 51 PM](https://user-images.githubusercontent.com/71450511/100524064-f4f2e280-3182-11eb-9f70-202ffa981ad7.png)

**Comment by jneilliii** [comment]
Did the plugin's settings get wiped out for some reason? Check in settings and make sure you have the commands configured for the other buttons.

![image](https://user-images.githubusercontent.com/5249455/100526666-18c12300-3199-11eb-8920-069fa9776d71.png)

**Comment by MarcWinNJ** [comment]
This is what is there. No M117 though
![Screen Shot 2020-11-28 at 6 34 33 PM](https://user-images.githubusercontent.com/71450511/100528243-904a7e80-31a8-11eb-89f4-00a11bd1aab0.png)

**Comment by jneilliii** [comment]
Ok, then definitely something else then. Can you check your browser's developer console (F12) for errors on initial page load please?

**Comment by MarcWinNJ** [comment]
Ok, will do, I have tried on both Chrome and Microsoft Edge. I am on a Mac.  I am having an issue with the Z Offset plugin as well. It will show men the variable but give me a circle with the line through it where I cannot make any changes. I am running the firmware from the Markin guy in Australia. And I have not updated to Octoprint 1.42 yes.

**Comment by MarcWinNJ** [comment]
Upgrading to release 1,4,2 fixed it

**Comment by MarcWinNJ** [comment]
I do have a question for you. On my BV install why does it always put me above the 0 line by a lot. On some runs I am at the zero mark and then if I run it again with no changes I am sure it is my start code Burt I am still learning. How do I get it to run at the 0 reference point.  Is it my offset.  

Mt BV code is: 


G28 0 ; Home all axes
@BEDLEVELVISUALIZER ; instruct plugin to start recording responses from printer.
G29 0 ; Auto bed-level (BL-Touch)
M420 S1 Z2 ; Uses bed mesh
M412 S0 ; Turn off filament runout sensor

>

**Comment by jneilliii** [comment]
It's best to keep these questions with the appropriate repo, but to answer your question, I have received reports of this recently and think it's related to broken firmware. I have a couple of guys in Discord doing some additional testing, as this does not happen with official Marlin 2.0.X and UBL.

**Comment by MarcWinNJ** [comment]
I am running firmware from the MarlinAU subscription site. Build was from Nov, 27.  Moved off of Creality and Smith to test since my BLTouch dopest seem to impact my prints positively
