### ISSUE TITLE
How can this Plugin be used?

### ISSUE THREAD

**Issue by MohammedNoureldin** [jneilliii/OctoPrint-BLTouch#22]
Hello,

this is not really an issue, but I am wondering how this plugin can be used? So could you mention please some use full cases for it? For example to re-level the bed, or anything else possible? It is being recommended by several resources online, but no one really mentioned how to use it correctly.

Thanks

**Comment by jneilliii** [comment]
that's funny. It just gives you buttons for controlling the BLTouch, ie for resetting etc. It doesn't really do anything else that you couldn't do just running the commands manually in terminal tab.
