### ISSUE TITLE
FYI - OctoPod added support for this plugin

### ISSUE THREAD

**Issue by gdombiak** [jneilliii/OctoPrint-BLTouch#23]
Hi @jneilliii, I added support for yet another one of your useful plugins. In this case there are no APIs but I rely on the settings of this plugin. Let me know if you (someday) remove or rename any of the settings. If in the future you prefer to expose this via an API I can change OctoPod to use the API.

Regards,
Gaston

**Comment by jneilliii** [comment]
Thanks @gdombiak I doubt I'll ever change this plugin too much, if at all because it's so specialized. It literally is just sending gcode commands.
