### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by jjl40** [jneilliii/OctoPrint-BLTouch#24]
I installed this plugin because I am having trouble with a new install of an SKR v1.4 turbo motherboard. I thought this would be easy since there are dedicated pins for the BL Touch but I am unable to home the Z axis. The probe deploys but the Z axis will not move. Thst is followed by Pronterface reporting an error. 

Error:!! STOP called because of BLTouch error - restart with M999
[ERROR] Error:!! STOP called because of BLTouch error - restart with M999

When I run the test with the plugin the probe deplys several times (maybe 10) but how do you tell if that is good or bad? Some documentation would be helpful. There are buttons that are not defined like RELEASE and PROBE BED. What probe method will be used?
I am trying to figure out what the purpose of this plugin is. It doesn't seem to be a good troubleshooting tool.

**Comment by jneilliii** [comment]
It is technically not a troubleshooting tool just a means to put buttons on the control tab to send the necessary gcode commands to the printer's firmware to perform the BLTouch operations. If you can't get your firmware to work with the BLTouch then this plugin isn't going to help you much in figuring out what's wrong with your firmware when you're attempting to probe.

**Comment by jjl40** [comment]
Hi jneilliii
Thanks for the prompt reply. Should I open another issue to request some documentation? I still would like to know what the buttons are for.
For instance, there is a test button but what are you testing or what is a good result? Is the probe bed button just a G30 or a G29 or what?

John Lytle

________________________________

**Comment by jneilliii** [comment]
Depending on which BLTouch you have, etc. maybe this will help you understand what the commands are.

https://www.antclabs.com/manual

**Comment by jjl40** [comment]
Hahaha

Yes! Even that is a better manual than the one that comes with the plugin.

John Lytle

________________________________

**Comment by jneilliii** [comment]
That's the point, it's a manual for the product you purchased. The plugin is just a tool to run those commands from the manual.

**Comment by jjl40** [comment]
The point is - even a Chenglish manual is better than nothing. Some tools also require instructions. 
Manual is overstating what is needed. Just a few sentences with expected results or, if that’s too much work, how about what G codes are produced when a button is pressed. 

Thanks anyway 

John Lytle
