### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by omnilogix** [jneilliii/OctoPrint-BLTouch#3]
It would be really great to add 1 additional button with multi-command script to perform a complete auto leveling sequence.

Mine looks like this:
G4 P5000	   ; delay while BLTouch starts up
M280 S10.6         ; make sure BLTouch is reset (pin might be too close to bed)
G4 P1000	   ; delay while BLTouch resets
G91 G1 Z10 F200    ; move away from bed incremental
G90                ; absolute moves
M280 S3.0          ; drop BLTouch pin
M561		   ; Clear any existing plane measurements
G32                ; calc bed compensation (config set to auto-home first)
G0 X171 Y171 F4000 ; go to center of bed 
G30                ; probe bed once
G30                ; probe bed twice
G30 Z2.75          ; set probe offset  (Increase to move 0 closer to bed, decrease to move away)
M280 S7            ; make sure BLTouch pin is raised

Thanks!!

**Comment by jneilliii** [comment]
Typically these types of operations are controlled by the start gcode of your slicer application and doesn't make sense to me to include as part of this plugin.  You could even generate this gcode file yourself and upload to OctoPrint and then run it anytime you want without the need for a plugin at all.

**Comment by omnilogix** [comment]
Agreed that this should be a startup operation (and it is), but in real life a re-leveling can be needed as often as every print if you have to wrestle your model off of the build plate, or the motors are powered down while applying pressure to the build plate (C-Bot designs).   In the interest of not having to go through a power cycle, and not having to scroll through the many gcode files I have to find a script, this feature would still add a lot of value for my use case.  After all, I have a BLTouch because bed leveling is very important to me, as is the ability to level when I feel the need.  Just food for thought!  You could even hide the button if no script is defined.

BTW: Nice plugin!
