### ISSUE TITLE
left and right buttons and home in between doesn't work

### ISSUE THREAD

**Issue by henrikkoch** [jneilliii/OctoPrint-BLTouch#4]
Im using this add-on. All buttons work except left, right and the home button in the middle for my Prusa i3MK2s/MM. The home button to the right between up and down works.

How can I get this to work?

I'm using OctoPrint Version 1.3.5 (rc/maintenance branch). I works fine when using it in a web browser but not when using it on a Touch screen using TouchUI (TouchUI (0.3.10))

**Comment by jneilliii** [comment]
I think you're posting an issue to the wrong repository.  I assume you are looking for TouchUI, this plugin is for controlling BLTouch probes.
