### ISSUE TITLE
Probe down not working

### ISSUE THREAD

**Issue by siblues** [jneilliii/OctoPrint-BLTouch#5]
I have everything wired up correctly and all of the g codes work when entered into the terminal on Octoprint.Three of the buttons on the plugin work great but the probe down doesn't work.I have checked how I entered the codes into the plugin and if I copy and paste the codes into the terminal they all work a they should.

**Comment by jneilliii** [comment]
Try changing the setting and saving, then restart octoprint and make sure to reload the web interface, holding the shift key down.
