### ISSUE TITLE
Please add two more options

### ISSUE THREAD

**Issue by Snakn1** [jneilliii/OctoPrint-BLTouch#8]
can you add two more option buttons. one for the prob test IE. G32 and one to save the config file IE. M500. I run a Smoothie BD and for now I changed the self test to the probe start (g32) and the reset alarm to M500 (save the tables) . but it would be nice to have all 4 options. 

thank you

**Comment by Snakn1** [comment]
Thank you for your time and consideration for this.

**Comment by jneilliii** [comment]
You can give the version linked below a test for me that would be great.  It adds the additional buttons (probe bed and save) that you can configure.

https://github.com/jneilliii/OctoPrint-BLTouch/archive/0.3.0.zip

**Comment by Snakn1** [comment]
Thanks I will let you know after I install it tomorrow.

Thanks
Brad

On Dec 28, 2018 2:35 PM, "jneilliii" <notifications@github.com> wrote:

You can give the version linked below a test for me that would be great. It
adds the additional buttons (probe bed and save) that you can configure.

https://github.com/jneilliii/OctoPrint-BLTouch/archive/0.3.0.zip

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jneilliii/OctoPrint-BLTouch/issues/8#issuecomment-450423107>,
or mute the thread

**Comment by Snakn1** [comment]
i just tried it and it is just what i needed, it works as i wished it to

Thank you very much

Brad
